name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setting env
      run: vcvarsall x86 10.0.22621.0

    - name: Build ${{matrix.configuration}}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: set INCLUDE=${{env.SOLUTION_FILE_PATH}}\Entropy\src ; msbuild /m /p:useenv=true /p:Configuration=${{matrix.configuration}} ${{env.SOLUTION_FILE_PATH}}
